### ISSUE TITLE
QuantileUtil.getQuantilesFromParams broken

### ISSUE THREAD

**Issue by pgieser** [LinkedInAttic/datafu#11]
QuantileUtil.getQuantilesFromParams("10") gives:

[0.0, 0.1111111111111111, 0.2222222222222222, 0.3333333333333333, 0.4444444444444444, 0.5555555555555556, 0.6666666666666667, 0.7777777777777779, 0.8888888888888891]

I discovered this when using the Quantile UDF with a single constructor argument and noticing that the last computed percentile did not match the max value in my dataset.

QuantileUtil.getQuantilesFromParams("0", ".1", ".2", ".3", ".4", ".5", ".6", ".7", ".8", ".9", "1") correctly gives:

[0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]

Pete

**Comment by matthayes** [comment]
Thanks for pointing this out.  I see where the bug is.

By the way, QuantileUtil.getQuantilesFromParams("10") should actually give:

[0.0, 0.1111111111111111, 0.2222222222222222, 0.3333333333333333, 0.4444444444444444, 0.5555555555555556, 0.6666666666666667, 0.7777777777777779, 0.8888888888888891,1.0]

The equivalent of:

QuantileUtil.getQuantilesFromParams("0", ".1", ".2", ".3", ".4", ".5", ".6", ".7", ".8", ".9", "1")

is:

QuantileUtil.getQuantilesFromParams("11")

**Comment by matthayes** [comment]
Fix checked in and more unit tests added!

**Comment by pgieser** [comment]
Thanks!  (yeah, I realized the inconsistency in my note after the fact but didn't think it was worth fixing :)

BTW, I also created a bug for this in jira that you may want to close out:

https://linkedin.jira.com/browse/DATAFU-5

Is there a plan to release a 0.0.5 version?
